name = "ohstatus"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-06-27"
compatibility_flags = ["nodejs_compat"]

workers_dev = false
preview_urls = false

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "ohstatus"
database_name = "ohstatus"
database_id = "f888f235-8e3f-458a-8ac1-9c5e5fae925d"
migrations_dir = "drizzle"


[[queues.producers]]
binding = "SUBSCRIBERS_QUEUE"
queue = "sync-subscribers"
